"""empty message

Revision ID: 09f7902d1cb2
Revises: f6434ddff8ff
Create Date: 2025-10-02 20:41:13.169227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09f7902d1cb2'
down_revision: Union[str, Sequence[str], None] = 'f6434ddff8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'prefix',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('currencies', 'exchange_rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'exchange_rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('currencies', 'prefix',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
