"""empty message

Revision ID: 0e13acd03419
Revises: f2755d43420c
Create Date: 2025-09-25 19:06:42.945463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e13acd03419'
down_revision: Union[str, Sequence[str], None] = 'f2755d43420c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    op.add_column('servers', sa.Column('modloader', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('servers', sa.Column('modlist', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.add_column('servers', sa.Column('moddownload', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('servers', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('compatible', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('modconditions', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('servers', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.add_column('servers', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    op.add_column('servers', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.add_column('servers', sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('servers', sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True))
    op.create_index(op.f('ix_servers_active'), 'servers', ['active'], unique=False)
    op.create_index(op.f('ix_servers_color'), 'servers', ['color'], unique=False)
    op.create_index(op.f('ix_servers_compatible'), 'servers', ['compatible'], unique=False)
    op.create_index(op.f('ix_servers_domain'), 'servers', ['domain'], unique=False)
    op.create_index(op.f('ix_servers_emoji'), 'servers', ['emoji'], unique=False)
    op.create_index(op.f('ix_servers_icon'), 'servers', ['icon'], unique=False)
    op.create_index(op.f('ix_servers_modconditions'), 'servers', ['modconditions'], unique=False)
    op.create_index(op.f('ix_servers_moddownload'), 'servers', ['moddownload'], unique=False)
    op.create_index(op.f('ix_servers_modlist'), 'servers', ['modlist'], unique=False)
    op.create_index(op.f('ix_servers_modloader'), 'servers', ['modloader'], unique=False)
    op.create_index(op.f('ix_servers_port'), 'servers', ['port'], unique=False)
    op.create_index(op.f('ix_servers_uuid'), 'servers', ['uuid'], unique=False)
    op.create_index(op.f('ix_servers_version'), 'servers', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_version'), table_name='servers')
    op.drop_index(op.f('ix_servers_uuid'), table_name='servers')
    op.drop_index(op.f('ix_servers_port'), table_name='servers')
    op.drop_index(op.f('ix_servers_modloader'), table_name='servers')
    op.drop_index(op.f('ix_servers_modlist'), table_name='servers')
    op.drop_index(op.f('ix_servers_moddownload'), table_name='servers')
    op.drop_index(op.f('ix_servers_modconditions'), table_name='servers')
    op.drop_index(op.f('ix_servers_icon'), table_name='servers')
    op.drop_index(op.f('ix_servers_emoji'), table_name='servers')
    op.drop_index(op.f('ix_servers_domain'), table_name='servers')
    op.drop_index(op.f('ix_servers_compatible'), table_name='servers')
    op.drop_index(op.f('ix_servers_color'), table_name='servers')
    op.drop_index(op.f('ix_servers_active'), table_name='servers')
    op.drop_column('servers', 'domain')
    op.drop_column('servers', 'uuid')
    op.drop_column('servers', 'emoji')
    op.drop_column('servers', 'port')
    op.drop_column('servers', 'color')
    op.drop_column('servers', 'icon')
    op.drop_column('servers', 'modconditions')
    op.drop_column('servers', 'compatible')
    op.drop_column('servers', 'active')
    op.drop_column('servers', 'moddownload')
    op.drop_column('servers', 'modlist')
    op.drop_column('servers', 'modloader')
    op.drop_column('servers', 'version')
    # ### end Alembic commands ###
