"""empty message

Revision ID: 14ae3697354b
Revises: 401440d821ca
Create Date: 2025-10-18 20:42:09.272559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14ae3697354b'
down_revision: Union[str, Sequence[str], None] = '401440d821ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency_from_id', sa.Integer(), nullable=True),
    sa.Column('currency_from_amount', sa.Float(), nullable=True),
    sa.Column('currency_to_id', sa.Integer(), nullable=True),
    sa.Column('currency_to_amount', sa.Float(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('result_text', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['currency_from_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_to_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_exchanges_code'), 'currency_exchanges', ['code'], unique=False)
    op.create_index(op.f('ix_currency_exchanges_id'), 'currency_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_currency_exchanges_result'), 'currency_exchanges', ['result'], unique=False)
    op.create_index(op.f('ix_currency_exchanges_result_text'), 'currency_exchanges', ['result_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_exchanges_result_text'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_result'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_id'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_code'), table_name='currency_exchanges')
    op.drop_table('currency_exchanges')
    # ### end Alembic commands ###
