"""empty message

Revision ID: 1adc9ab5aff6
Revises: a35f12e4db7a
Create Date: 2025-10-11 14:23:28.029894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1adc9ab5aff6'
down_revision: Union[str, Sequence[str], None] = 'a35f12e4db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blackjackgame_code'), table_name='blackjackgame')
    op.drop_index(op.f('ix_blackjackgame_id'), table_name='blackjackgame')
    op.drop_index(op.f('ix_blackjackgame_result'), table_name='blackjackgame')
    op.drop_table('blackjackgame')
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.create_table('blackjackgame',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_hand', mysql.JSON(), nullable=False),
    sa.Column('dealer_hand', mysql.JSON(), nullable=False),
    sa.Column('currency_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bet', mysql.FLOAT(), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('blackjackgame_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('blackjackgame_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_blackjackgame_result'), 'blackjackgame', ['result'], unique=False)
    op.create_index(op.f('ix_blackjackgame_id'), 'blackjackgame', ['id'], unique=False)
    op.create_index(op.f('ix_blackjackgame_code'), 'blackjackgame', ['code'], unique=False)
    # ### end Alembic commands ###
