"""empty message

Revision ID: 2461ba3232b8
Revises: fcf15c5f81d4
Create Date: 2025-10-18 22:12:06.366328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2461ba3232b8'
down_revision: Union[str, Sequence[str], None] = 'fcf15c5f81d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_exchanges', 'result',
               existing_type=mysql.VARCHAR(length=4),
               type_=sqlmodel.sql.sqltypes.AutoString(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_exchanges', 'result',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
