"""empty message

Revision ID: 342d24aeaf4b
Revises: 2461ba3232b8
Create Date: 2025-10-18 22:32:41.875999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '342d24aeaf4b'
down_revision: Union[str, Sequence[str], None] = '2461ba3232b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_exchanges_result_text'), table_name='currency_exchanges')
    op.drop_column('currency_exchanges', 'result_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_exchanges', sa.Column('result_text', mysql.VARCHAR(length=300), nullable=True))
    op.create_index(op.f('ix_currency_exchanges_result_text'), 'currency_exchanges', ['result_text'], unique=False)
    # ### end Alembic commands ###
