"""empty message

Revision ID: 401440d821ca
Revises: c13272bab6aa
Create Date: 2025-10-14 20:07:25.540758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '401440d821ca'
down_revision: Union[str, Sequence[str], None] = 'c13272bab6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('assigned_by_default', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_permissions_assigned_by_default'), 'permissions', ['assigned_by_default'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_assigned_by_default'), table_name='permissions')
    op.drop_column('permissions', 'assigned_by_default')
    # ### end Alembic commands ###
