"""empty message

Revision ID: 485af3ef3edf
Revises: c9a9ca924994
Create Date: 2025-10-11 17:08:10.315817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '485af3ef3edf'
down_revision: Union[str, Sequence[str], None] = 'c9a9ca924994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackjack_games', sa.Column('user_hand_value', sa.Integer(), nullable=False))
    op.add_column('blackjack_games', sa.Column('dealer_hand_value', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_blackjack_games_dealer_hand_value'), 'blackjack_games', ['dealer_hand_value'], unique=False)
    op.create_index(op.f('ix_blackjack_games_user_hand_value'), 'blackjack_games', ['user_hand_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blackjack_games_user_hand_value'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_dealer_hand_value'), table_name='blackjack_games')
    op.drop_column('blackjack_games', 'dealer_hand_value')
    op.drop_column('blackjack_games', 'user_hand_value')
    # ### end Alembic commands ###
