"""empty message

Revision ID: 4973ccee48f0
Revises: aa63a2ba057c
Create Date: 2026-06-21 16:45:46.950878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4973ccee48f0'
down_revision: Union[str, Sequence[str], None] = 'aa63a2ba057c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_ratings', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_ratings', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
