"""empty message

Revision ID: 49a4bdc7b3c2
Revises: 939985a3b4d3
Create Date: 2025-10-11 22:13:14.276176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49a4bdc7b3c2'
down_revision: Union[str, Sequence[str], None] = '939985a3b4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_can_add_games'), table_name='users')
    op.drop_column('users', 'can_add_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_add_games', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_can_add_games'), 'users', ['can_add_games'], unique=False)
    # ### end Alembic commands ###
