"""empty message

Revision ID: 4a2e376df78a
Revises: b77865998dd0
Create Date: 2025-09-30 15:38:49.697999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a2e376df78a'
down_revision: Union[str, Sequence[str], None] = 'b77865998dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_ratings', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_game_ratings_date_added'), table_name='game_ratings')
    op.create_index(op.f('ix_game_ratings_last_updated'), 'game_ratings', ['last_updated'], unique=False)
    op.drop_column('game_ratings', 'date_added')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_ratings', sa.Column('date_added', mysql.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_game_ratings_last_updated'), table_name='game_ratings')
    op.create_index(op.f('ix_game_ratings_date_added'), 'game_ratings', ['date_added'], unique=False)
    op.drop_column('game_ratings', 'last_updated')
    # ### end Alembic commands ###
