"""empty message

Revision ID: 500443f2a44b
Revises: cc8514174360
Create Date: 2025-10-18 21:01:15.201186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '500443f2a44b'
down_revision: Union[str, Sequence[str], None] = 'cc8514174360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_exchanges', sa.Column('relative_exchange_rate', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_currency_exchanges_currency_from_exchange_rate'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_currency_to_exchange_rate'), table_name='currency_exchanges')
    op.create_index(op.f('ix_currency_exchanges_relative_exchange_rate'), 'currency_exchanges', ['relative_exchange_rate'], unique=False)
    op.drop_column('currency_exchanges', 'currency_to_exchange_rate')
    op.drop_column('currency_exchanges', 'currency_from_exchange_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_exchanges', sa.Column('currency_from_exchange_rate', mysql.FLOAT(), nullable=False))
    op.add_column('currency_exchanges', sa.Column('currency_to_exchange_rate', mysql.FLOAT(), nullable=False))
    op.drop_index(op.f('ix_currency_exchanges_relative_exchange_rate'), table_name='currency_exchanges')
    op.create_index(op.f('ix_currency_exchanges_currency_to_exchange_rate'), 'currency_exchanges', ['currency_to_exchange_rate'], unique=False)
    op.create_index(op.f('ix_currency_exchanges_currency_from_exchange_rate'), 'currency_exchanges', ['currency_from_exchange_rate'], unique=False)
    op.drop_column('currency_exchanges', 'relative_exchange_rate')
    # ### end Alembic commands ###
