"""empty message

Revision ID: 50408e371734
Revises: 49a4bdc7b3c2
Create Date: 2025-10-12 11:14:01.731844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50408e371734'
down_revision: Union[str, Sequence[str], None] = '49a4bdc7b3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_categories', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('server_categories', 'is_minecraft',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('servers', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('servers', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('servers', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('servers', 'version',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('servers', 'modloader',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('servers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('servers', 'is_compatible',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('servers', 'emoji',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('servers', 'uuid',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=8),
               nullable=False)
    op.alter_column('servers', 'domain',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('servers', 'port',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_servers_category'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_foreign_key(None, 'servers', 'server_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('servers', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('category', mysql.VARCHAR(length=25), nullable=True))
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    op.create_index(op.f('ix_servers_category'), 'servers', ['category'], unique=False)
    op.alter_column('servers', 'port',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('servers', 'domain',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('servers', 'uuid',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=8),
               type_=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('servers', 'emoji',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('servers', 'is_compatible',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('servers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('servers', 'modloader',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('servers', 'version',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('servers', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('servers', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.drop_column('servers', 'category_id')
    op.alter_column('server_categories', 'is_minecraft',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('server_categories', 'name',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
