"""empty message

Revision ID: 5723f475c08a
Revises: 5247875424a2
Create Date: 2025-09-27 15:09:17.110624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5723f475c08a'
down_revision: Union[str, Sequence[str], None] = '5247875424a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('install_size', sa.Integer(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('banner_link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('min_party_size', sa.Integer(), nullable=False),
    sa.Column('max_party_size', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('update_banner_link', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_average_rating'), 'games', ['average_rating'], unique=False)
    op.create_index(op.f('ix_games_banner_link'), 'games', ['banner_link'], unique=False)
    op.create_index(op.f('ix_games_date_added'), 'games', ['date_added'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_install_size'), 'games', ['install_size'], unique=False)
    op.create_index(op.f('ix_games_last_updated'), 'games', ['last_updated'], unique=False)
    op.create_index(op.f('ix_games_link'), 'games', ['link'], unique=False)
    op.create_index(op.f('ix_games_max_party_size'), 'games', ['max_party_size'], unique=False)
    op.create_index(op.f('ix_games_min_party_size'), 'games', ['min_party_size'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_platform'), 'games', ['platform'], unique=False)
    op.create_index(op.f('ix_games_popularity_score'), 'games', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_games_update_banner_link'), 'games', ['update_banner_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_update_banner_link'), table_name='games')
    op.drop_index(op.f('ix_games_popularity_score'), table_name='games')
    op.drop_index(op.f('ix_games_platform'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_min_party_size'), table_name='games')
    op.drop_index(op.f('ix_games_max_party_size'), table_name='games')
    op.drop_index(op.f('ix_games_link'), table_name='games')
    op.drop_index(op.f('ix_games_last_updated'), table_name='games')
    op.drop_index(op.f('ix_games_install_size'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_date_added'), table_name='games')
    op.drop_index(op.f('ix_games_banner_link'), table_name='games')
    op.drop_index(op.f('ix_games_average_rating'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
