"""empty message

Revision ID: 5d7c281566ce
Revises: 342d24aeaf4b
Create Date: 2025-10-19 21:51:31.191707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d7c281566ce'
down_revision: Union[str, Sequence[str], None] = '342d24aeaf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackjack_games', sa.Column('expires', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_blackjack_games_result_text'), table_name='blackjack_games')
    op.create_index(op.f('ix_blackjack_games_expires'), 'blackjack_games', ['expires'], unique=False)
    op.drop_column('blackjack_games', 'result_text')
    op.add_column('currency_exchanges', sa.Column('expires', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_currency_exchanges_expires'), 'currency_exchanges', ['expires'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_exchanges_expires'), table_name='currency_exchanges')
    op.drop_column('currency_exchanges', 'expires')
    op.add_column('blackjack_games', sa.Column('result_text', mysql.VARCHAR(length=300), nullable=True))
    op.drop_index(op.f('ix_blackjack_games_expires'), table_name='blackjack_games')
    op.create_index(op.f('ix_blackjack_games_result_text'), 'blackjack_games', ['result_text'], unique=False)
    op.drop_column('blackjack_games', 'expires')
    # ### end Alembic commands ###
