"""empty message

Revision ID: 61f0b29b04a2
Revises: a98d2abd990d
Create Date: 2026-06-25 17:01:45.057870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61f0b29b04a2'
down_revision: Union[str, Sequence[str], None] = 'a98d2abd990d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_servers_creation_date'), 'servers', ['creation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_creation_date'), table_name='servers')
    op.drop_column('servers', 'creation_date')
    # ### end Alembic commands ###
