"""empty message

Revision ID: 6c6735b18710
Revises: db7a9d8be75a
Create Date: 2025-09-25 21:59:17.012167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c6735b18710'
down_revision: Union[str, Sequence[str], None] = 'db7a9d8be75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servercategories_color'), table_name='servercategories')
    op.drop_index(op.f('ix_servercategories_icon'), table_name='servercategories')
    op.drop_index(op.f('ix_servercategories_id'), table_name='servercategories')
    op.drop_index(op.f('ix_servercategories_is_minecraft'), table_name='servercategories')
    op.drop_index(op.f('ix_servercategories_name'), table_name='servercategories')
    op.drop_table('servercategories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servercategories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('is_minecraft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_servercategories_name'), 'servercategories', ['name'], unique=False)
    op.create_index(op.f('ix_servercategories_is_minecraft'), 'servercategories', ['is_minecraft'], unique=False)
    op.create_index(op.f('ix_servercategories_id'), 'servercategories', ['id'], unique=False)
    op.create_index(op.f('ix_servercategories_icon'), 'servercategories', ['icon'], unique=False)
    op.create_index(op.f('ix_servercategories_color'), 'servercategories', ['color'], unique=False)
    # ### end Alembic commands ###
