"""empty message

Revision ID: 6dc5caca0476
Revises: 1dffd6320d12
Create Date: 2025-10-01 16:09:44.456435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dc5caca0476'
down_revision: Union[str, Sequence[str], None] = '1dffd6320d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('banner_image', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_games_banner_image'), 'games', ['banner_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_banner_image'), table_name='games')
    op.drop_column('games', 'banner_image')
    # ### end Alembic commands ###
