"""empty message

Revision ID: 7c75580cd45b
Revises: 5723f475c08a
Create Date: 2025-09-27 16:00:42.576623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c75580cd45b'
down_revision: Union[str, Sequence[str], None] = '5723f475c08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'last_updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
