"""empty message

Revision ID: 84fb89ac9daf
Revises: bed78556c78e
Create Date: 2025-09-25 21:35:16.962169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84fb89ac9daf'
down_revision: Union[str, Sequence[str], None] = 'bed78556c78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=False)
    # ### end Alembic commands ###
