"""empty message

Revision ID: 85aefc28ea1a
Revises: 61f0b29b04a2
Create Date: 2026-06-25 21:35:57.906011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85aefc28ea1a'
down_revision: Union[str, Sequence[str], None] = '61f0b29b04a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_categories', sa.Column('servers_icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('server_categories', sa.Column('minecraft_icon', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.drop_index(op.f('ix_server_categories_icon'), table_name='server_categories')
    op.create_index(op.f('ix_server_categories_minecraft_icon'), 'server_categories', ['minecraft_icon'], unique=False)
    op.create_index(op.f('ix_server_categories_servers_icon'), 'server_categories', ['servers_icon'], unique=False)
    op.drop_column('server_categories', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_categories', sa.Column('icon', mysql.VARCHAR(length=45), nullable=True))
    op.drop_index(op.f('ix_server_categories_servers_icon'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_minecraft_icon'), table_name='server_categories')
    op.create_index(op.f('ix_server_categories_icon'), 'server_categories', ['icon'], unique=False)
    op.drop_column('server_categories', 'minecraft_icon')
    op.drop_column('server_categories', 'servers_icon')
    # ### end Alembic commands ###
