"""empty message

Revision ID: 939985a3b4d3
Revises: 
Create Date: 2025-10-11 20:26:33.465271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '939985a3b4d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('can_gamble', sa.Boolean(), nullable=False),
    sa.Column('can_exchange', sa.Boolean(), nullable=False),
    sa.Column('can_work_for', sa.Boolean(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('value_multiplier', sa.Float(), nullable=False),
    sa.Column('starting_value', sa.Float(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_can_exchange'), 'currencies', ['can_exchange'], unique=False)
    op.create_index(op.f('ix_currencies_can_gamble'), 'currencies', ['can_gamble'], unique=False)
    op.create_index(op.f('ix_currencies_can_work_for'), 'currencies', ['can_work_for'], unique=False)
    op.create_index(op.f('ix_currencies_color'), 'currencies', ['color'], unique=False)
    op.create_index(op.f('ix_currencies_decimal_places'), 'currencies', ['decimal_places'], unique=False)
    op.create_index(op.f('ix_currencies_display_name'), 'currencies', ['display_name'], unique=False)
    op.create_index(op.f('ix_currencies_exchange_rate'), 'currencies', ['exchange_rate'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    op.create_index(op.f('ix_currencies_prefix'), 'currencies', ['prefix'], unique=False)
    op.create_index(op.f('ix_currencies_starting_value'), 'currencies', ['starting_value'], unique=False)
    op.create_index(op.f('ix_currencies_value_multiplier'), 'currencies', ['value_multiplier'], unique=False)
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_tags_id'), 'game_tags', ['id'], unique=False)
    op.create_index(op.f('ix_game_tags_name'), 'game_tags', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_index(op.f('ix_permissions_description'), 'permissions', ['description'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_issued_at'), 'refresh_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_subject'), 'refresh_tokens', ['subject'], unique=False)
    op.create_table('server_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('is_minecraft', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_categories_color'), 'server_categories', ['color'], unique=False)
    op.create_index(op.f('ix_server_categories_icon'), 'server_categories', ['icon'], unique=False)
    op.create_index(op.f('ix_server_categories_id'), 'server_categories', ['id'], unique=False)
    op.create_index(op.f('ix_server_categories_is_minecraft'), 'server_categories', ['is_minecraft'], unique=False)
    op.create_index(op.f('ix_server_categories_name'), 'server_categories', ['name'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('modloader', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('modlist', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('moddownload', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_compatible', sa.Boolean(), nullable=True),
    sa.Column('modconditions', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_category'), 'servers', ['category'], unique=False)
    op.create_index(op.f('ix_servers_color'), 'servers', ['color'], unique=False)
    op.create_index(op.f('ix_servers_description'), 'servers', ['description'], unique=False)
    op.create_index(op.f('ix_servers_domain'), 'servers', ['domain'], unique=False)
    op.create_index(op.f('ix_servers_emoji'), 'servers', ['emoji'], unique=False)
    op.create_index(op.f('ix_servers_icon'), 'servers', ['icon'], unique=False)
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_index(op.f('ix_servers_is_active'), 'servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_servers_is_compatible'), 'servers', ['is_compatible'], unique=False)
    op.create_index(op.f('ix_servers_modconditions'), 'servers', ['modconditions'], unique=False)
    op.create_index(op.f('ix_servers_moddownload'), 'servers', ['moddownload'], unique=False)
    op.create_index(op.f('ix_servers_modlist'), 'servers', ['modlist'], unique=False)
    op.create_index(op.f('ix_servers_modloader'), 'servers', ['modloader'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=False)
    op.create_index(op.f('ix_servers_port'), 'servers', ['port'], unique=False)
    op.create_index(op.f('ix_servers_uuid'), 'servers', ['uuid'], unique=False)
    op.create_index(op.f('ix_servers_version'), 'servers', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar_link', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('first_site_login', sa.DateTime(), nullable=True),
    sa.Column('last_site_login', sa.DateTime(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('display_name_last_changed', sa.DateTime(), nullable=True),
    sa.Column('can_use_site', sa.Boolean(), nullable=True),
    sa.Column('can_add_games', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_avatar_link'), 'users', ['avatar_link'], unique=False)
    op.create_index(op.f('ix_users_can_add_games'), 'users', ['can_add_games'], unique=False)
    op.create_index(op.f('ix_users_can_use_site'), 'users', ['can_use_site'], unique=False)
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=False)
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_display_name_last_changed'), 'users', ['display_name_last_changed'], unique=False)
    op.create_index(op.f('ix_users_first_site_login'), 'users', ['first_site_login'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_site_login'), 'users', ['last_site_login'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('blackjack_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_hand', sa.JSON(), nullable=False),
    sa.Column('user_hand_value', sa.Integer(), nullable=False),
    sa.Column('dealer_hand', sa.JSON(), nullable=False),
    sa.Column('dealer_hand_value', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('bet', sa.Float(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('result_text', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_games_code'), 'blackjack_games', ['code'], unique=False)
    op.create_index(op.f('ix_blackjack_games_dealer_hand_value'), 'blackjack_games', ['dealer_hand_value'], unique=False)
    op.create_index(op.f('ix_blackjack_games_id'), 'blackjack_games', ['id'], unique=False)
    op.create_index(op.f('ix_blackjack_games_result'), 'blackjack_games', ['result'], unique=False)
    op.create_index(op.f('ix_blackjack_games_result_text'), 'blackjack_games', ['result_text'], unique=False)
    op.create_index(op.f('ix_blackjack_games_user_hand_value'), 'blackjack_games', ['user_hand_value'], unique=False)
    op.create_table('cooldowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cooldown_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooldowns_cooldown_type'), 'cooldowns', ['cooldown_type'], unique=False)
    op.create_index(op.f('ix_cooldowns_id'), 'cooldowns', ['id'], unique=False)
    op.create_table('games',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('min_party_size', sa.Integer(), nullable=False),
    sa.Column('max_party_size', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_size', sa.Integer(), nullable=True),
    sa.Column('banner_link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('banner_image', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('update_banner_link', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_average_rating'), 'games', ['average_rating'], unique=False)
    op.create_index(op.f('ix_games_banner_image'), 'games', ['banner_image'], unique=False)
    op.create_index(op.f('ix_games_banner_link'), 'games', ['banner_link'], unique=False)
    op.create_index(op.f('ix_games_date_added'), 'games', ['date_added'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_install_size'), 'games', ['install_size'], unique=False)
    op.create_index(op.f('ix_games_last_updated'), 'games', ['last_updated'], unique=False)
    op.create_index(op.f('ix_games_link'), 'games', ['link'], unique=False)
    op.create_index(op.f('ix_games_max_party_size'), 'games', ['max_party_size'], unique=False)
    op.create_index(op.f('ix_games_min_party_size'), 'games', ['min_party_size'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_platform'), 'games', ['platform'], unique=False)
    op.create_index(op.f('ix_games_popularity_score'), 'games', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_games_update_banner_link'), 'games', ['update_banner_link'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('min_pay', sa.Float(), nullable=False),
    sa.Column('max_pay', sa.Float(), nullable=False),
    sa.Column('cooldown', sa.Float(), nullable=False),
    sa.Column('overridden_currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['overridden_currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_cooldown'), 'jobs', ['cooldown'], unique=False)
    op.create_index(op.f('ix_jobs_display_name'), 'jobs', ['display_name'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_max_pay'), 'jobs', ['max_pay'], unique=False)
    op.create_index(op.f('ix_jobs_min_pay'), 'jobs', ['min_pay'], unique=False)
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    op.create_table('user_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_currencies_id'), 'user_currencies', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('game_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_ratings_id'), 'game_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_game_ratings_last_updated'), 'game_ratings', ['last_updated'], unique=False)
    op.create_index(op.f('ix_game_ratings_rating'), 'game_ratings', ['rating'], unique=False)
    op.create_table('user_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_jobs_id'), 'user_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jobs_id'), table_name='user_jobs')
    op.drop_table('user_jobs')
    op.drop_index(op.f('ix_game_ratings_rating'), table_name='game_ratings')
    op.drop_index(op.f('ix_game_ratings_last_updated'), table_name='game_ratings')
    op.drop_index(op.f('ix_game_ratings_id'), table_name='game_ratings')
    op.drop_table('game_ratings')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_user_currencies_id'), table_name='user_currencies')
    op.drop_table('user_currencies')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_min_pay'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_max_pay'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_display_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_cooldown'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_games_update_banner_link'), table_name='games')
    op.drop_index(op.f('ix_games_popularity_score'), table_name='games')
    op.drop_index(op.f('ix_games_platform'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_min_party_size'), table_name='games')
    op.drop_index(op.f('ix_games_max_party_size'), table_name='games')
    op.drop_index(op.f('ix_games_link'), table_name='games')
    op.drop_index(op.f('ix_games_last_updated'), table_name='games')
    op.drop_index(op.f('ix_games_install_size'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_date_added'), table_name='games')
    op.drop_index(op.f('ix_games_banner_link'), table_name='games')
    op.drop_index(op.f('ix_games_banner_image'), table_name='games')
    op.drop_index(op.f('ix_games_average_rating'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_cooldowns_id'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_cooldown_type'), table_name='cooldowns')
    op.drop_table('cooldowns')
    op.drop_index(op.f('ix_blackjack_games_user_hand_value'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_result_text'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_result'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_id'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_dealer_hand_value'), table_name='blackjack_games')
    op.drop_index(op.f('ix_blackjack_games_code'), table_name='blackjack_games')
    op.drop_table('blackjack_games')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_site_login'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_site_login'), table_name='users')
    op.drop_index(op.f('ix_users_display_name_last_changed'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_index(op.f('ix_users_can_use_site'), table_name='users')
    op.drop_index(op.f('ix_users_can_add_games'), table_name='users')
    op.drop_index(op.f('ix_users_avatar_link'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servers_version'), table_name='servers')
    op.drop_index(op.f('ix_servers_uuid'), table_name='servers')
    op.drop_index(op.f('ix_servers_port'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_modloader'), table_name='servers')
    op.drop_index(op.f('ix_servers_modlist'), table_name='servers')
    op.drop_index(op.f('ix_servers_moddownload'), table_name='servers')
    op.drop_index(op.f('ix_servers_modconditions'), table_name='servers')
    op.drop_index(op.f('ix_servers_is_compatible'), table_name='servers')
    op.drop_index(op.f('ix_servers_is_active'), table_name='servers')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_icon'), table_name='servers')
    op.drop_index(op.f('ix_servers_emoji'), table_name='servers')
    op.drop_index(op.f('ix_servers_domain'), table_name='servers')
    op.drop_index(op.f('ix_servers_description'), table_name='servers')
    op.drop_index(op.f('ix_servers_color'), table_name='servers')
    op.drop_index(op.f('ix_servers_category'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_server_categories_name'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_is_minecraft'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_id'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_icon'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_color'), table_name='server_categories')
    op.drop_table('server_categories')
    op.drop_index(op.f('ix_refresh_tokens_subject'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_issued_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_description'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_game_tags_name'), table_name='game_tags')
    op.drop_index(op.f('ix_game_tags_id'), table_name='game_tags')
    op.drop_table('game_tags')
    op.drop_index(op.f('ix_currencies_value_multiplier'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_starting_value'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_prefix'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_exchange_rate'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_display_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_decimal_places'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_color'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_work_for'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_gamble'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_exchange'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
