"""empty message

Revision ID: 9e9f5f09fe1d
Revises: 4bd839f8975e
Create Date: 2025-10-09 21:48:42.093731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e9f5f09fe1d'
down_revision: Union[str, Sequence[str], None] = '4bd839f8975e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cooldowns_expires'), table_name='cooldowns')
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.create_index(op.f('ix_cooldowns_expires'), 'cooldowns', ['expires'], unique=False)
    # ### end Alembic commands ###
