"""empty message

Revision ID: a35f12e4db7a
Revises: 9e9f5f09fe1d
Create Date: 2025-10-11 14:20:57.326250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a35f12e4db7a'
down_revision: Union[str, Sequence[str], None] = '9e9f5f09fe1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackjackgame', sa.Column('user_hand', sa.JSON(), nullable=False))
    op.add_column('blackjackgame', sa.Column('dealer_hand', sa.JSON(), nullable=False))
    op.add_column('blackjackgame', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.add_column('blackjackgame', sa.Column('bet', sa.Float(), nullable=True))
    op.add_column('blackjackgame', sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False))
    op.create_index(op.f('ix_blackjackgame_result'), 'blackjackgame', ['result'], unique=False)
    op.create_foreign_key(None, 'blackjackgame', 'currencies', ['currency_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_constraint(None, 'blackjackgame', type_='foreignkey')
    op.drop_index(op.f('ix_blackjackgame_result'), table_name='blackjackgame')
    op.drop_column('blackjackgame', 'result')
    op.drop_column('blackjackgame', 'bet')
    op.drop_column('blackjackgame', 'currency_id')
    op.drop_column('blackjackgame', 'dealer_hand')
    op.drop_column('blackjackgame', 'user_hand')
    # ### end Alembic commands ###
