"""empty message

Revision ID: a98d2abd990d
Revises: aa0556ffdb9f
Create Date: 2026-06-25 11:46:48.229053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a98d2abd990d'
down_revision: Union[str, Sequence[str], None] = 'aa0556ffdb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_refresh_tokens_subject'), table_name='refresh_tokens')
    op.add_column('server_categories', sa.Column('servers_color', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    op.add_column('server_categories', sa.Column('minecraft_color', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    op.drop_index(op.f('ix_server_categories_color'), table_name='server_categories')
    op.create_index(op.f('ix_server_categories_minecraft_color'), 'server_categories', ['minecraft_color'], unique=False)
    op.create_index(op.f('ix_server_categories_servers_color'), 'server_categories', ['servers_color'], unique=False)
    op.drop_column('server_categories', 'color')
    op.add_column('servers', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('servers', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_servers_is_private'), 'servers', ['is_private'], unique=False)
    op.create_foreign_key(None, 'servers', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_index(op.f('ix_servers_is_private'), table_name='servers')
    op.drop_column('servers', 'game_id')
    op.drop_column('servers', 'is_private')
    op.add_column('server_categories', sa.Column('color', mysql.VARCHAR(length=25), nullable=True))
    op.drop_index(op.f('ix_server_categories_servers_color'), table_name='server_categories')
    op.drop_index(op.f('ix_server_categories_minecraft_color'), table_name='server_categories')
    op.create_index(op.f('ix_server_categories_color'), 'server_categories', ['color'], unique=False)
    op.drop_column('server_categories', 'minecraft_color')
    op.drop_column('server_categories', 'servers_color')
    #op.create_index(op.f('ix_refresh_tokens_subject'), 'refresh_tokens', ['subject'], unique=False)
    # ### end Alembic commands ###
