"""empty message

Revision ID: aa0556ffdb9f
Revises: 17ac4ef7449e
Create Date: 2026-06-24 11:26:44.728991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa0556ffdb9f'
down_revision: Union[str, Sequence[str], None] = '17ac4ef7449e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('banner_image', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_servers_banner_image'), 'servers', ['banner_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_banner_image'), table_name='servers')
    op.drop_column('servers', 'banner_image')
    # ### end Alembic commands ###
