"""empty message

Revision ID: aa63a2ba057c
Revises: cc2247f6ad9a
Create Date: 2026-06-18 14:29:36.269275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa63a2ba057c'
down_revision: Union[str, Sequence[str], None] = 'cc2247f6ad9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_image', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.create_index(op.f('ix_users_avatar_image'), 'users', ['avatar_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_avatar_image'), table_name='users')
    op.drop_column('users', 'avatar_image')
    # ### end Alembic commands ###
