"""empty message

Revision ID: b500b134dff0
Revises: 7c75580cd45b
Create Date: 2025-09-27 16:22:32.386629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b500b134dff0'
down_revision: Union[str, Sequence[str], None] = '7c75580cd45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'average_rating',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('games', 'popularity_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'popularity_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('games', 'average_rating',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
