"""empty message

Revision ID: bed78556c78e
Revises: c3a95bc201b5
Create Date: 2025-09-25 21:33:42.301868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bed78556c78e'
down_revision: Union[str, Sequence[str], None] = 'c3a95bc201b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'avatar_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_site_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'last_site_login',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'display_name_last_changed',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name_last_changed',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'last_site_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'first_site_login',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'avatar_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
