"""empty message

Revision ID: c13272bab6aa
Revises: 50408e371734
Create Date: 2025-10-12 13:42:45.060420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c13272bab6aa'
down_revision: Union[str, Sequence[str], None] = '50408e371734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False))
    op.create_index(op.f('ix_servers_display_name'), 'servers', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_display_name'), table_name='servers')
    op.drop_column('servers', 'display_name')
    # ### end Alembic commands ###
