"""empty message

Revision ID: c3a95bc201b5
Revises: f161bbe5667a
Create Date: 2025-09-25 20:22:55.352619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3a95bc201b5'
down_revision: Union[str, Sequence[str], None] = 'f161bbe5667a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('is_compatible', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_servers_active'), table_name='servers')
    op.drop_index(op.f('ix_servers_compatible'), table_name='servers')
    op.create_index(op.f('ix_servers_is_active'), 'servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_servers_is_compatible'), 'servers', ['is_compatible'], unique=False)
    op.drop_column('servers', 'compatible')
    op.drop_column('servers', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('compatible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_servers_is_compatible'), table_name='servers')
    op.drop_index(op.f('ix_servers_is_active'), table_name='servers')
    op.create_index(op.f('ix_servers_compatible'), 'servers', ['compatible'], unique=False)
    op.create_index(op.f('ix_servers_active'), 'servers', ['active'], unique=False)
    op.drop_column('servers', 'is_compatible')
    op.drop_column('servers', 'is_active')
    # ### end Alembic commands ###
