"""empty message

Revision ID: c9a9ca924994
Revises: 21873e9aaa2c
Create Date: 2025-10-11 16:08:43.353634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9a9ca924994'
down_revision: Union[str, Sequence[str], None] = '21873e9aaa2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blackjack_games', sa.Column('result_text', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.alter_column('blackjack_games', 'result',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.create_index(op.f('ix_blackjack_games_result_text'), 'blackjack_games', ['result_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blackjack_games_result_text'), table_name='blackjack_games')
    op.alter_column('blackjack_games', 'result',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.drop_column('blackjack_games', 'result_text')
    # ### end Alembic commands ###
