"""empty message

Revision ID: cc2247f6ad9a
Revises: 7a106463b524
Create Date: 2025-11-29 22:49:15.692609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc2247f6ad9a'
down_revision: Union[str, Sequence[str], None] = '7a106463b524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('is_running', sa.Boolean(), nullable=False))
    op.add_column('servers', sa.Column('time_started', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_servers_is_running'), 'servers', ['is_running'], unique=False)
    op.create_index(op.f('ix_servers_time_started'), 'servers', ['time_started'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_time_started'), table_name='servers')
    op.drop_index(op.f('ix_servers_is_running'), table_name='servers')
    op.drop_column('servers', 'time_started')
    op.drop_column('servers', 'is_running')
    # ### end Alembic commands ###
