"""empty message

Revision ID: cc2be59c9b3d
Revises: 8418e7fd3fca
Create Date: 2025-09-28 21:51:39.709103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc2be59c9b3d'
down_revision: Union[str, Sequence[str], None] = '8418e7fd3fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'banner_link',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'banner_link',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
