"""empty message

Revision ID: cc8514174360
Revises: 14ae3697354b
Create Date: 2025-10-18 20:58:35.210659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc8514174360'
down_revision: Union[str, Sequence[str], None] = '14ae3697354b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_exchanges', sa.Column('currency_from_exchange_rate', sa.Float(), nullable=False))
    op.add_column('currency_exchanges', sa.Column('currency_to_exchange_rate', sa.Float(), nullable=False))
    op.create_index(op.f('ix_currency_exchanges_currency_from_exchange_rate'), 'currency_exchanges', ['currency_from_exchange_rate'], unique=False)
    op.create_index(op.f('ix_currency_exchanges_currency_to_exchange_rate'), 'currency_exchanges', ['currency_to_exchange_rate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_exchanges_currency_to_exchange_rate'), table_name='currency_exchanges')
    op.drop_index(op.f('ix_currency_exchanges_currency_from_exchange_rate'), table_name='currency_exchanges')
    op.drop_column('currency_exchanges', 'currency_to_exchange_rate')
    op.drop_column('currency_exchanges', 'currency_from_exchange_rate')
    # ### end Alembic commands ###
