"""empty message

Revision ID: d75f5a022dec
Revises: 85aefc28ea1a
Create Date: 2026-06-25 22:43:51.972094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd75f5a022dec'
down_revision: Union[str, Sequence[str], None] = '85aefc28ea1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'description',
               existing_type=mysql.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
