"""empty message

Revision ID: e070f5d82ab2
Revises: 84fb89ac9daf
Create Date: 2025-09-25 21:50:54.414649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e070f5d82ab2'
down_revision: Union[str, Sequence[str], None] = '84fb89ac9daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_key'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('apikey_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_apikey_key'), 'apikey', ['key'], unique=True)
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    # ### end Alembic commands ###
