"""empty message

Revision ID: f081856234b0
Revises: 2910ac58de96
Create Date: 2025-10-07 22:46:23.696607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f081856234b0'
down_revision: Union[str, Sequence[str], None] = '2910ac58de96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooldowns', sa.Column('expires', sa.DateTime(), nullable=False))
    op.add_column('cooldowns', sa.Column('cooldown_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.create_index(op.f('ix_cooldowns_cooldown_type'), 'cooldowns', ['cooldown_type'], unique=False)
    op.create_index(op.f('ix_cooldowns_expires'), 'cooldowns', ['expires'], unique=False)
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_cooldowns_expires'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_cooldown_type'), table_name='cooldowns')
    op.drop_column('cooldowns', 'cooldown_type')
    op.drop_column('cooldowns', 'expires')
    # ### end Alembic commands ###
