"""empty message

Revision ID: f2755d43420c
Revises: 
Create Date: 2025-09-25 18:50:27.757984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2755d43420c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    op.create_index(op.f('ix_servers_category'), 'servers', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_category'), table_name='servers')
    op.drop_column('servers', 'category')
    # ### end Alembic commands ###
