"""empty message

Revision ID: f391c385da7c
Revises: b212f124bf69
Create Date: 2025-10-07 18:50:07.912750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f391c385da7c'
down_revision: Union[str, Sequence[str], None] = 'b212f124bf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_currencies_id'), table_name='user_currencies')
    op.drop_table('user_currencies')
    op.add_column('currencies', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.alter_column('currencies', 'id',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.alter_column('currencies', 'id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('currencies', 'name')
    op.create_table('user_currencies',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency_id', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('balance', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('user_currencies_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_currencies_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_currencies_id'), 'user_currencies', ['id'], unique=False)
    # ### end Alembic commands ###
