"""empty message

Revision ID: f6434ddff8ff
Revises: 8f44eb4da49a
Create Date: 2025-10-02 20:39:17.809418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6434ddff8ff'
down_revision: Union[str, Sequence[str], None] = '8f44eb4da49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('can_gamble', sa.Boolean(), nullable=False),
    sa.Column('can_exchange', sa.Boolean(), nullable=False),
    sa.Column('can_work_for', sa.Boolean(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('value_multiplier', sa.Float(), nullable=False),
    sa.Column('starting_value', sa.Float(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_can_exchange'), 'currencies', ['can_exchange'], unique=False)
    op.create_index(op.f('ix_currencies_can_gamble'), 'currencies', ['can_gamble'], unique=False)
    op.create_index(op.f('ix_currencies_can_work_for'), 'currencies', ['can_work_for'], unique=False)
    op.create_index(op.f('ix_currencies_color'), 'currencies', ['color'], unique=False)
    op.create_index(op.f('ix_currencies_decimal_places'), 'currencies', ['decimal_places'], unique=False)
    op.create_index(op.f('ix_currencies_display_name'), 'currencies', ['display_name'], unique=False)
    op.create_index(op.f('ix_currencies_exchange_rate'), 'currencies', ['exchange_rate'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_prefix'), 'currencies', ['prefix'], unique=False)
    op.create_index(op.f('ix_currencies_starting_value'), 'currencies', ['starting_value'], unique=False)
    op.create_index(op.f('ix_currencies_value_multiplier'), 'currencies', ['value_multiplier'], unique=False)
    op.drop_index(op.f('ix_currency_can_exchange'), table_name='currency')
    op.drop_index(op.f('ix_currency_can_gamble'), table_name='currency')
    op.drop_index(op.f('ix_currency_can_work_for'), table_name='currency')
    op.drop_index(op.f('ix_currency_color'), table_name='currency')
    op.drop_index(op.f('ix_currency_decimal_places'), table_name='currency')
    op.drop_index(op.f('ix_currency_display_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_exchange_rate'), table_name='currency')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_prefix'), table_name='currency')
    op.drop_index(op.f('ix_currency_starting_value'), table_name='currency')
    op.drop_index(op.f('ix_currency_value_multiplier'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('prefix', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('can_gamble', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_exchange', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('can_work_for', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('exchange_rate', mysql.FLOAT(), nullable=False),
    sa.Column('decimal_places', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value_multiplier', mysql.FLOAT(), nullable=False),
    sa.Column('starting_value', mysql.FLOAT(), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_currency_value_multiplier'), 'currency', ['value_multiplier'], unique=False)
    op.create_index(op.f('ix_currency_starting_value'), 'currency', ['starting_value'], unique=False)
    op.create_index(op.f('ix_currency_prefix'), 'currency', ['prefix'], unique=False)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_index(op.f('ix_currency_exchange_rate'), 'currency', ['exchange_rate'], unique=False)
    op.create_index(op.f('ix_currency_display_name'), 'currency', ['display_name'], unique=False)
    op.create_index(op.f('ix_currency_decimal_places'), 'currency', ['decimal_places'], unique=False)
    op.create_index(op.f('ix_currency_color'), 'currency', ['color'], unique=False)
    op.create_index(op.f('ix_currency_can_work_for'), 'currency', ['can_work_for'], unique=False)
    op.create_index(op.f('ix_currency_can_gamble'), 'currency', ['can_gamble'], unique=False)
    op.create_index(op.f('ix_currency_can_exchange'), 'currency', ['can_exchange'], unique=False)
    op.drop_index(op.f('ix_currencies_value_multiplier'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_starting_value'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_prefix'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_exchange_rate'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_display_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_decimal_places'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_color'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_work_for'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_gamble'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_can_exchange'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
