name: Release to GitHub Container Registry

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ./
        push: true
        no-cache: true
        tags: |
          ghcr.io/mrspacecarrot/derpscubedapi:latest
          ghcr.io/mrspacecarrot/derpscubedapi:${{ github.event.release.tag_name }}